In [1]:
import numpy as np

In [9]:
array1 = np.array([10, 20, 30])
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
print(array1)
print(ndarray)

[10 20 30]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(type(array1))
print(type(ndarray))
print(type(ndarray[0][1]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [12]:
print(array1.shape)
print(ndarray.shape)

(3,)
(3, 3)


In [18]:
array2 = np.array([[1, 2, 3]], dtype=np.uint8) # dtype {uint8(画像処理), float32(データ保存でよく使う), float64(学習でよく使う)}
print(array2)
print(type(array2))
print(type(array2[0][0]))
print(array2.shape)

[[1 2 3]]
<class 'numpy.ndarray'>
<class 'numpy.uint8'>
(1, 3)


In [19]:
ndarray.astype(np.float64)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## ndarrayの演算

In [21]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [22]:
a = [1, 2, 3]
b = [1, 2, 3]
a + b

[1, 2, 3, 1, 2, 3]

In [25]:
array3 = np.array([1, 2, 3], dtype=np.float32)
array1 + array3  # Broadcasting

array([[ 2.,  4.,  6.],
       [ 5.,  7.,  9.],
       [ 8., 10., 12.]])

In [26]:
array1 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Shape

In [30]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
print(ndarray)
print(f'Shape:{ndarray.shape}')

[[1 2]
 [3 4]
 [5 6]]
Shape:(3, 2)


In [34]:
ndarray = ndarray.reshape(2, 3)
print(ndarray)
print(f'Shape:{ndarray.shape}')

[[1 2 3]
 [4 5 6]]
Shape:(2, 3)


In [36]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])
print(ndarray1)
print(ndarray2)
print(ndarray1.shape) # ベクトル rank1
print(ndarray2.shape) # 1行３列　rank2

[1 2 3]
[[1 2 3]]
(3,)
(1, 3)


In [40]:
# expand_dims
ndarray1_ax0 = np.expand_dims(ndarray1, axis=0)
ndarray1_ax1 = np.expand_dims(ndarray1, axis=1) # 0(最初) or -1(最後)に追加することが多い
print(ndarray1_ax0)
print(ndarray1_ax1)
print(ndarray1_ax0.shape)
print(ndarray1_ax1.shape) 

[[1 2 3]]
[[1]
 [2]
 [3]]
(1, 3)
(3, 1)


In [44]:
# squeeze
ndarray1 = np.squeeze(ndarray1_ax0)
print(ndarray1)
print(ndarray1.shape)

[1 2 3]
(3,)


In [54]:
# flatten
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray = ndarray.flatten()
print(ndarray)
print(ndarray.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


## Indexing, Slicing

In [71]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(ndarray)
print('>>>>Indexing')
print(ndarray[0][1])
print(ndarray[0, 1])
print('>>>>Slicing')
print(ndarray[:1])
print(ndarray[:-1])
print('##########')
print(ndarray[1:])
print('##########')
print(ndarray[1:, 1:])
print(ndarray[1:][1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
>>>>Indexing
2
2
>>>>Slicing
[[1 2 3]]
[[1 2 3]
 [4 5 6]]
##########
[[4 5 6]
 [7 8 9]]
##########
[[5 6]
 [8 9]]
[[7 8 9]]


## np.arange()

In [74]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [78]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

## np.linspace()

In [80]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## np.logspace()

In [88]:
np.logspace(0, 3, num=50, base=10, endpoint=True) # base**start, base**stop

array([   1.        ,    1.1513954 ,    1.32571137,    1.52641797,
          1.75751062,    2.02358965,    2.32995181,    2.6826958 ,
          3.0888436 ,    3.55648031,    4.09491506,    4.71486636,
          5.42867544,    6.25055193,    7.19685673,    8.28642773,
          9.54095476,   10.98541142,   12.64855217,   14.56348478,
         16.76832937,   19.30697729,   22.22996483,   25.59547923,
         29.47051703,   33.93221772,   39.06939937,   44.98432669,
         51.79474679,   59.63623317,   68.6648845 ,   79.06043211,
         91.0298178 ,  104.81131342,  120.67926406,  138.94954944,
        159.98587196,  184.20699693,  212.09508879,  244.20530945,
        281.1768698 ,  323.74575428,  372.75937203,  429.19342601,
        494.17133613,  568.9866029 ,  655.12855686,  754.31200634,
        868.51137375, 1000.        ])

In [86]:
np.linspace(0, 3, 50)

array([0.        , 0.06122449, 0.12244898, 0.18367347, 0.24489796,
       0.30612245, 0.36734694, 0.42857143, 0.48979592, 0.55102041,
       0.6122449 , 0.67346939, 0.73469388, 0.79591837, 0.85714286,
       0.91836735, 0.97959184, 1.04081633, 1.10204082, 1.16326531,
       1.2244898 , 1.28571429, 1.34693878, 1.40816327, 1.46938776,
       1.53061224, 1.59183673, 1.65306122, 1.71428571, 1.7755102 ,
       1.83673469, 1.89795918, 1.95918367, 2.02040816, 2.08163265,
       2.14285714, 2.20408163, 2.26530612, 2.32653061, 2.3877551 ,
       2.44897959, 2.51020408, 2.57142857, 2.63265306, 2.69387755,
       2.75510204, 2.81632653, 2.87755102, 2.93877551, 3.        ])

In [87]:
10**0.06122449

1.1513953998675057

## np.zeros()

In [89]:
shape = (3, 4n)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
np.zeros(3)

array([0., 0., 0.])

## np.ones()

In [91]:
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [92]:
np.ones(shape)*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

## np.eye()

In [94]:
# I: identify matrix(単位行列)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## np.random  乱数生成

### np.random.rand()

In [100]:
# 疑似乱数　pseudo random
np.random.rand(3, 3)

array([[0.47674609, 0.32600473, 0.6036402 ],
       [0.88641212, 0.81847555, 0.46037157],
       [0.9468124 , 0.89239545, 0.31256549]])

### np.random.seed

In [104]:
# seedを使うことで自分の作成したコードやモデルを再現できる
np.random.seed(1)
np.random.rand()

0.417022004702574

In [105]:
np.random.seed(2)
np.random.rand()

0.43599490214200376

In [106]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [107]:
np.random.seed(2)
np.random.rand()

0.43599490214200376

### np.random.randn()

In [109]:
# 標準正規分布(standerd normal distribution：平均０、分散１)からランダムに値を取ってくる 
np.random.randn()

-1.3542305422856002

In [115]:
np.random.randn(4, 4, 3) # ０から離れるに従って出てくる確率が低くなる

array([[[-1.90906996,  0.46970571,  0.43018817],
        [ 0.66538996, -0.84862911, -0.15564226],
        [-0.94180036,  0.38720095, -0.28394322],
        [ 0.97557339,  1.0061689 , -0.71352523]],

       [[ 1.13765608,  0.60455917, -1.29860708],
        [ 0.66953579, -0.1310936 , -1.25054639],
        [ 1.57510078, -0.3420158 ,  1.01886728],
        [ 0.52118032, -0.59525288, -1.69188736]],

       [[-0.19549318,  0.76777205, -0.67122674],
        [-0.46446161,  0.3206774 , -0.13877577],
        [ 1.22922429,  0.10322178, -1.06284593],
        [-0.87537696, -0.54931033,  1.92094412]],

       [[-0.95377368,  0.24735332, -0.47310459],
        [ 0.62346659,  0.34521518, -0.87419789],
        [-0.04721554, -1.2942452 ,  0.23928756],
        [ 2.44065937,  0.32268866, -0.49701162]]])

In [116]:
# 任意の平均・標準偏差の正規分布からランダムに値を取ってくる
np.random.normal(loc=5, scale=1)

5.939637027234937

### np.random.randint()

In [118]:
np.random.randint(100, 1000, size=(3, 3)) # min以上、max以下

array([[987, 600, 789],
       [431, 915, 244],
       [266, 530, 603]])

In [120]:
np.random.randint(100, size=(3, 3)) # min以下

array([[87, 88, 52],
       [25,  2, 71],
       [37,  9, 10]])

### np.random.choice()

In [125]:
a = np.arange(100, 1000)
np.random.choice(a, size=(3, 3))

array([[154, 752, 707],
       [616, 579, 970],
       [766, 814, 178]])

## 統計量を求める

In [163]:
std_norm = np.random.randn(5, 5)
std_norm

array([[ 1.12292902, -0.55813836,  1.30055285,  0.1074227 , -0.22479833],
       [-0.03182945,  0.57047924, -0.29344409, -0.32782973,  1.98516925],
       [ 0.34497425,  1.83738722, -0.62088372, -0.13981617,  1.57701072],
       [-0.56838417, -0.29747365, -1.44320235, -0.72280447,  0.64433789],
       [ 0.74075826,  0.40849809, -1.20427552, -1.7138368 ,  0.09753986]])

In [128]:
# 最大値
std_norm.max()

1.6690244177302602

In [129]:
np.max(std_norm)

1.6690244177302602

In [130]:
# 最小値
std_norm.min()

-2.011755945596503

In [131]:
# indexを取得
std_norm.argmax()

6

In [132]:
std_norm.argmin()

23

In [135]:
std_norm.flatten()[23]

-2.011755945596503

In [136]:
# 平均
std_norm.mean()

0.05237906131121541

In [146]:
std_norm = np.random.randn(100, 100)
std_norm.mean()

0.0001575250790649438

In [148]:
# 中央値 ndarrayから直接使えない
# 中央値：平均値より時間が掛かるが、外れ値に強い
np.median(std_norm)

0.01315542481549151

In [159]:
# 中央値　vs 平均値
import time
a = np.random.randn(5000, 5000)

before = time.time()
np.median(a)
median_after = time.time()
np.mean(a)
mean_after = time.time()

median_time = median_after - before
mean_time = mean_after - median_after
print(f'中央値タイム：{median_time:.4f}\n平均値タイム{mean_time:.4f}')

中央値タイム：0.3425
平均値タイム0.0163


In [160]:
# 標準偏差(standerd deviation)：分散の平方根(平均との差を２乗した合計を、データ数で割った(⇨分散)の正の平方根)
np.std(std_norm)

1.0121642902404917

In [165]:
std_norm = np.random.randn(5, 5)
std_norm

array([[ 1.9437272 ,  1.10050041, -0.34908495, -0.13517138, -0.02563076],
       [-0.99374866, -1.55248548, -1.1666949 ,  0.06037767,  0.02047705],
       [ 0.47479982, -1.57556775,  0.40291614,  0.63564453,  1.7523048 ],
       [ 0.54744554,  0.78194404,  0.86401327, -0.89723332,  0.65063274],
       [ 0.22223772, -0.21011374,  0.40794903, -0.51590231,  0.54166763]])

In [166]:
# 各統計量を行・列ごとに求めることもできる
std_norm.max(axis=0) # 1＝行、0＝列

array([1.9437272 , 1.10050041, 0.86401327, 0.63564453, 1.7523048 ])

## 数学で使える便利関数

In [167]:
# 平方根(square root)
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [168]:
# log(logarithim) 
np.log(1)

0.0

In [171]:
x = np.linspace(1, 10, 10)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [172]:
np.log(x) # 底がe

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [173]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809])

In [174]:
2*1.5849625

3.169925

In [177]:
# 指数関数(exponential function)
np.exp(1) # e**1

2.718281828459045

In [178]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [179]:
# ネイピア数
np.e

2.718281828459045

In [180]:
# 合計(summation)
np.sum(x)

55.0

In [182]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [185]:
ndarray = array.reshape(2, 5)
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [186]:
np.sum(ndarray, axis=0)

array([ 7,  9, 11, 13, 15])

In [188]:
# 絶対値(absolute value)
array = np.arange(-10, 0)
array

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [189]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## np.nan

In [191]:
# NaN (Not a Number)
np.log(-100)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


nan

In [194]:
print(np.nan)
print(type(np.nan))

nan
<class 'float'>


## np.isnan()

In [195]:
np.isnan(np.log(-100))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

In [199]:
a = None
print(a is None)
print(np.log(-100) is np.nan)

True
False


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


In [200]:
print(a == None)
print(np.log(-100) == np.nan)

True
False


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


## その他の便利関数

### np.clip()

In [202]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [204]:
1e-4

0.0001

### numpy arrayのcondition

In [212]:
# np.where
array_mean = array.mean()
np.where(array > array_mean, 1, 0)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [216]:
np.where(array > array_mean) # tupleで返ってくる

(array([5, 6, 7, 8, 9]),)

In [218]:
result, = np.where(array > array_mean) # unpack
result

array([5, 6, 7, 8, 9])

In [214]:
# filter
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [215]:
array[array>3]

array([4, 5, 6, 7, 8, 9])

In [220]:
ndarray = array.reshape(2, 5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [221]:
ndarray[ndarray>3] # フラットで返ってくる

array([4, 5, 6, 7, 8, 9])

In [223]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [224]:
# .all() 全てTrueか
(ndarray > 3).all()

False

In [225]:
# .any() 1つでもTrueか
(ndarray > 3).any()

True

In [226]:
(ndarray > 3).any(axis=0)

array([ True,  True,  True,  True,  True])

In [228]:
# .unique()
array = np.array([1, 1, 1, 2, 2, 3, 4, 5, 5, ])
np.unique(array)

array([1, 2, 3, 4, 5])

In [229]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5]), array([3, 2, 1, 1, 2]))

In [231]:
# .bincount()
np.bincount(array)

array([0, 3, 2, 1, 1, 2])

## 結合

### np.concatenate()

In [233]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [234]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [241]:
concat_array = np.concatenate([ndarray_even, ndarray_odd], axis=0)
print(concat_array)
print(concat_array.shape)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
(6, 3)


### np.stack()

In [247]:
stacked_array = np.stack([ndarray_even, ndarray_odd], axis=-1) #rankが上がる
print(stacked_array) 
print(stacked_array.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
(3, 3, 2)


## 転置

### np.transpose

In [252]:
ndarray = np.random.randn(3, 4)
print(ndarray)
print(ndarray.shape)

[[-0.74300721 -0.25944691 -0.48124919 -0.58650962]
 [-0.26769349 -0.7534122   0.15329614  2.45407791]
 [ 0.60007415  1.48473606  0.2092099  -1.37706636]]
(3, 4)


In [254]:
transpose_ndarray = np.transpose(ndarray)
print(transpose_ndarray)
print(transpose_ndarray.shape)

[[-0.74300721 -0.26769349  0.60007415]
 [-0.25944691 -0.7534122   1.48473606]
 [-0.48124919  0.15329614  0.2092099 ]
 [-0.58650962  2.45407791 -1.37706636]]
(4, 3)


### .T

In [255]:
ndarray.T

array([[-0.74300721, -0.26769349,  0.60007415],
       [-0.25944691, -0.7534122 ,  1.48473606],
       [-0.48124919,  0.15329614,  0.2092099 ],
       [-0.58650962,  2.45407791, -1.37706636]])

In [256]:
ndarray = np.random.randn(3, 4, 5)
print(ndarray)
print(ndarray.shape)

[[[ 1.25403246 -1.01193676  1.27178317 -0.01712724  0.35746218]
  [ 0.49713201  0.1642062  -1.93280286 -0.40280338  0.01168894]
  [-1.11073364  0.87947353  0.82287149 -0.47368618 -0.44842273]
  [-0.46973705  0.89880186  0.90505387  0.64407133 -0.71648378]]

 [[-0.88297202  0.3151718  -2.00607059 -1.55713524  1.69168186]
  [-0.51427423  0.83092666  0.70391843 -1.10888509  0.72074806]
  [ 0.67813457  0.54809869  1.23224482 -0.0900731   0.90398495]
  [-1.24848919 -0.04504477 -0.69171949 -0.25596898  1.94478729]]

 [[ 0.36718428 -0.67319047  0.60852409  2.89078207  0.50089228]
  [-0.61287696  1.36189024 -2.0656455   1.33874651 -0.72756411]
  [ 1.17094244 -0.20578971  1.38367962  1.01695884  0.18148825]
  [ 0.52967838 -1.68889488 -1.80526502 -1.61802388 -0.95721762]]]
(3, 4, 5)


In [257]:
t_ndarray = ndarray.T
print(t_ndarray)
print(t_ndarray.shape)

[[[ 1.25403246 -0.88297202  0.36718428]
  [ 0.49713201 -0.51427423 -0.61287696]
  [-1.11073364  0.67813457  1.17094244]
  [-0.46973705 -1.24848919  0.52967838]]

 [[-1.01193676  0.3151718  -0.67319047]
  [ 0.1642062   0.83092666  1.36189024]
  [ 0.87947353  0.54809869 -0.20578971]
  [ 0.89880186 -0.04504477 -1.68889488]]

 [[ 1.27178317 -2.00607059  0.60852409]
  [-1.93280286  0.70391843 -2.0656455 ]
  [ 0.82287149  1.23224482  1.38367962]
  [ 0.90505387 -0.69171949 -1.80526502]]

 [[-0.01712724 -1.55713524  2.89078207]
  [-0.40280338 -1.10888509  1.33874651]
  [-0.47368618 -0.0900731   1.01695884]
  [ 0.64407133 -0.25596898 -1.61802388]]

 [[ 0.35746218  1.69168186  0.50089228]
  [ 0.01168894  0.72074806 -0.72756411]
  [-0.44842273  0.90398495  0.18148825]
  [-0.71648378  1.94478729 -0.95721762]]]
(5, 4, 3)


In [260]:
ndarray = np.random.randn(3)
t_ndarray = ndarray.T
print(ndarray, ndarray.shape)
print(t_ndarray, ndarray.shape)

[-1.88307531  1.00242873 -0.51375386] (3,)
[-1.88307531  1.00242873 -0.51375386] (3,)


## 保存とロード

### np.save('path', array)

In [263]:
ndarray = np.random.randn(3, 3, 4)
ndarray

array([[[ 1.43343311,  0.45388047,  1.72877763, -1.44211674],
        [-0.10134675, -1.23756778,  0.74824579, -1.41366068],
        [ 0.5388907 , -0.28123534, -0.85894469,  0.33120112]],

       [[-0.55184313,  0.83167269,  0.79092835,  0.74293905],
        [ 0.62181874, -1.64881166,  0.75694783, -0.12416543],
        [-0.09835038,  0.16733208, -1.52018227,  0.41127172]],

       [[ 0.00611452,  0.87175253, -1.04422002,  1.21595639],
        [ 0.18474742,  0.28206611, -0.56315646,  1.96816445],
        [-0.43035318, -0.18808028,  0.24025142,  0.58675504]]])

In [265]:
np.save('data/sample_ndarray', ndarray)

### np.load('path')

In [267]:
loaded_ndarray = np.load('data/sample_ndarray.npy')
loaded_ndarray

array([[[ 1.43343311,  0.45388047,  1.72877763, -1.44211674],
        [-0.10134675, -1.23756778,  0.74824579, -1.41366068],
        [ 0.5388907 , -0.28123534, -0.85894469,  0.33120112]],

       [[-0.55184313,  0.83167269,  0.79092835,  0.74293905],
        [ 0.62181874, -1.64881166,  0.75694783, -0.12416543],
        [-0.09835038,  0.16733208, -1.52018227,  0.41127172]],

       [[ 0.00611452,  0.87175253, -1.04422002,  1.21595639],
        [ 0.18474742,  0.28206611, -0.56315646,  1.96816445],
        [-0.43035318, -0.18808028,  0.24025142,  0.58675504]]])

### save発展

In [270]:
dictionary = {
    'id': 19910104,
    'image': ndarray
}
dictionary

{'id': 19910104,
 'image': array([[[ 1.43343311,  0.45388047,  1.72877763, -1.44211674],
         [-0.10134675, -1.23756778,  0.74824579, -1.41366068],
         [ 0.5388907 , -0.28123534, -0.85894469,  0.33120112]],
 
        [[-0.55184313,  0.83167269,  0.79092835,  0.74293905],
         [ 0.62181874, -1.64881166,  0.75694783, -0.12416543],
         [-0.09835038,  0.16733208, -1.52018227,  0.41127172]],
 
        [[ 0.00611452,  0.87175253, -1.04422002,  1.21595639],
         [ 0.18474742,  0.28206611, -0.56315646,  1.96816445],
         [-0.43035318, -0.18808028,  0.24025142,  0.58675504]]])}

In [271]:
np.save('data/sample_dict', dictionary)

In [275]:
# pythonではobjectをpickleという形式で保存する
loaded_dict = np.load('data/sample_dict.npy', allow_pickle=True) # arrayで返ってくる
loaded_dict

array({'id': 19910104, 'image': array([[[ 1.43343311,  0.45388047,  1.72877763, -1.44211674],
        [-0.10134675, -1.23756778,  0.74824579, -1.41366068],
        [ 0.5388907 , -0.28123534, -0.85894469,  0.33120112]],

       [[-0.55184313,  0.83167269,  0.79092835,  0.74293905],
        [ 0.62181874, -1.64881166,  0.75694783, -0.12416543],
        [-0.09835038,  0.16733208, -1.52018227,  0.41127172]],

       [[ 0.00611452,  0.87175253, -1.04422002,  1.21595639],
        [ 0.18474742,  0.28206611, -0.56315646,  1.96816445],
        [-0.43035318, -0.18808028,  0.24025142,  0.58675504]]])},
      dtype=object)

In [278]:
a = np.array({'a': 1})
a

array({'a': 1}, dtype=object)

In [279]:
a[()]

{'a': 1}

In [ ]:
load